---
abstract: 'root namespace for Krisy Kreme modules'
author:
  - 'Curtis Brandt <curtis@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.019
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-KrispyKreme
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/aggrolite/WWW-KrispyKreme/issues
  homepage: https://github.com/aggrolite/WWW-KrispyKreme
  repository: https://github.com/aggrolite/WWW-KrispyKreme.git
version: 0.01
x_contributors:
  - 'Curtis Brandt <curtisjbrandt@gmail.com>'
